# Generated by Django 4.1.3 on 2022-11-08 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Emailni kiriting')),
                ('massage', models.CharField(max_length=100, verbose_name='Textni kiriting')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=60, verbose_name='Qayerdan')),
                ('to', models.CharField(max_length=60, verbose_name='Qayerga')),
                ('outbound', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('Return', models.DateTimeField(auto_now_add=True, verbose_name='Qaytish vaqti')),
                ('children', models.IntegerField(verbose_name='Bolalar soni')),
                ('Class', models.CharField(choices=[('Ecanomy', 'Ecanomy'), ('First', 'First'), ('Business', 'Business')], max_length=50, verbose_name='Klass')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('count', models.IntegerField(verbose_name='Joylar soni')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Mehmonxona nomi')),
                ('rooms', models.IntegerField(verbose_name='Xonalar soni')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
